### ISSUE TITLE
Software Sources (and elsewhere): banner merges with sidebar highlight

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-19.1-beta#75]
**Describe the bug**
In software Sources (and, one might suspect - but I cannot confirm - elsewhere), the banner (when there is one) merges with the highlighted element in the sidebar.

**To Reproduce**
1. Open Software Sources
2. Change a mirror.

**Expected behavior**
It would be best were the banner (the message about one's configuration having changed) not to merge (colour-wise) into the highlighted item ('official repositories') in the window's sidebar.

**Frequency**
Does the issue happen:
- [X] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [X] Cinnamon Edition
- [ ] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install
- [ ] Live session

**Screenshots**

![image](https://user-images.githubusercontent.com/9998846/50022671-df577300-ffd4-11e8-8938-d0ae3107d0db.png)

**Locale:**
```
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

```
**Drivers:**
```
Graphics:
  Device-1: InnoTek Systemberatung VirtualBox Graphics Adapter 
  driver: vboxvideo v: 5.2.23 r127298 bus ID: 00:02.0 chip ID: 80ee:beef 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  alternate: vboxvideo resolution: 1920x1120~60Hz 
  OpenGL: renderer: Chromium v: 2.1 Chromium 1.9 direct render: Yes 
```

**Additional context - my themes**
_Borders_: Mint-Y Dark (well, actually, I am using a customised version of that theme, but the problem occurs with the standard Mint-Y Dark too - and the Software Sources window does not honour my custom theme - but perhaps that is a problem with my theme).
_Icons_: Mint-X Dark
_Controls_: Mint-Y Dark
_Desktop_: Mint-Y Dark
